/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.iftm.pay.screens;

import javax.swing.JFrame;

/**
 *
 * @author IFTM
 */
public class Pay extends JFrame {

    /**
     * Creates new form Pay
     */
    public Pay() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPage = new javax.swing.JDesktopPane();
        MenuBar = new javax.swing.JMenuBar();
        ManagmentMenu = new javax.swing.JMenu();
        CustomerMenu = new javax.swing.JMenuItem();
        ProductMenu = new javax.swing.JMenuItem();
        InventoryMenu = new javax.swing.JMenuItem();
        CustomersMenu = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Testando Solução");
        setName("frame"); // NOI18N

        MainPage.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout MainPageLayout = new javax.swing.GroupLayout(MainPage);
        MainPage.setLayout(MainPageLayout);
        MainPageLayout.setHorizontalGroup(
            MainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 798, Short.MAX_VALUE)
        );
        MainPageLayout.setVerticalGroup(
            MainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );

        ManagmentMenu.setText("Gerenciamento");

        CustomerMenu.setText("Clientes");
        CustomerMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerMenuActionPerformed(evt);
            }
        });
        ManagmentMenu.add(CustomerMenu);

        ProductMenu.setText("Produtos");
        ProductMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductMenuActionPerformed(evt);
            }
        });
        ManagmentMenu.add(ProductMenu);

        InventoryMenu.setText("Estoque");
        InventoryMenu.setToolTipText("");
        ManagmentMenu.add(InventoryMenu);

        MenuBar.add(ManagmentMenu);
        MenuBar.add(CustomersMenu);

        jMenu1.setText("outros");
        MenuBar.add(jMenu1);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPage)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPage, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CustomerMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomerMenuActionPerformed

    private void ProductMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Pay frame = new Pay();
                frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CustomerMenu;
    private javax.swing.JMenu CustomersMenu;
    private javax.swing.JMenuItem InventoryMenu;
    private javax.swing.JDesktopPane MainPage;
    private javax.swing.JMenu ManagmentMenu;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenuItem ProductMenu;
    private javax.swing.JMenu jMenu1;
    // End of variables declaration//GEN-END:variables
}
