/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.iftm.pay.views;

import br.edu.iftm.pay.models.CustomerTableModel;
import br.edu.iftm.pay.models.ProductTableModel;
import br.edu.iftm.pay.views.createscreen.CreateCustomerInternalFrame;
import br.edu.iftm.pay.views.createscreen.CreateProductInternalFrame;
import java.awt.CardLayout;
import javax.swing.JFrame;

/**
 *
 * @author IFTM
 */
public class Pay extends JFrame {
    
    // create screens
    public CreateCustomerInternalFrame createCustomer = new CreateCustomerInternalFrame();
    public CreateProductInternalFrame createProduct = new CreateProductInternalFrame();
    
    // table model
    public static CustomerTableModel customerTableModel = new CustomerTableModel();
    public static ProductTableModel productTableModel = new ProductTableModel();
    
    /**
     * Creates new form Pay
     */
    public Pay() {
        initComponents();
        
        jTableCustomer.setModel(customerTableModel);
        jTableProduct.setModel(productTableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jContainerScreens = new javax.swing.JPanel();
        jRegisterScreen = new javax.swing.JPanel();
        jScreen = new javax.swing.JDesktopPane();
        jOrderRegisterScreen = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTableOrder = new javax.swing.JTable();
        jCustomerRegisterScreen = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableCustomer = new javax.swing.JTable();
        jProductRegisterScreen = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableProduct = new javax.swing.JTable();
        jPymentRegisterScreen = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablePayment = new javax.swing.JTable();
        jInventoryRegisterScreen = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableInventory = new javax.swing.JTable();
        jMenuBar = new javax.swing.JMenuBar();
        jRegistersMenu = new javax.swing.JMenu();
        jOrderMenuItem = new javax.swing.JMenuItem();
        jCustomerMenuItem = new javax.swing.JMenuItem();
        jProductMenuItem = new javax.swing.JMenuItem();
        jPaymentMenuItem = new javax.swing.JMenuItem();
        jInventoryMenuItem = new javax.swing.JMenuItem();
        jCustomerMenu = new javax.swing.JMenu();
        jCustomerRegisterMenuItem = new javax.swing.JMenuItem();
        jCustomerUpdateMenuItem = new javax.swing.JMenuItem();
        jCustomerRemoveMenuItem = new javax.swing.JMenuItem();
        jProductMenu = new javax.swing.JMenu();
        jProductRegisterMenuItem = new javax.swing.JMenuItem();
        jProductUpdateMenuItem = new javax.swing.JMenuItem();
        jProductRemoveMenuItem = new javax.swing.JMenuItem();
        jOrderMenu = new javax.swing.JMenu();
        jOrderRegisterMenuItem = new javax.swing.JMenuItem();
        jOrderUpdateMenuItem = new javax.swing.JMenuItem();
        jOrderRemoveMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Gerenciamento de Pedidos e registro de Pagamento - PV");
        setName("frame"); // NOI18N
        setResizable(false);

        jContainerScreens.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jScreenLayout = new javax.swing.GroupLayout(jScreen);
        jScreen.setLayout(jScreenLayout);
        jScreenLayout.setHorizontalGroup(
            jScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
        );
        jScreenLayout.setVerticalGroup(
            jScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jRegisterScreenLayout = new javax.swing.GroupLayout(jRegisterScreen);
        jRegisterScreen.setLayout(jRegisterScreenLayout);
        jRegisterScreenLayout.setHorizontalGroup(
            jRegisterScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScreen)
        );
        jRegisterScreenLayout.setVerticalGroup(
            jRegisterScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScreen, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jContainerScreens.add(jRegisterScreen, "RegisterScreen");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/pedido-icone.png"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(40, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel1.setText("Registro de pedidos:");

        jTableOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(jTableOrder);

        javax.swing.GroupLayout jOrderRegisterScreenLayout = new javax.swing.GroupLayout(jOrderRegisterScreen);
        jOrderRegisterScreen.setLayout(jOrderRegisterScreenLayout);
        jOrderRegisterScreenLayout.setHorizontalGroup(
            jOrderRegisterScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jOrderRegisterScreenLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jOrderRegisterScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 906, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jOrderRegisterScreenLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jOrderRegisterScreenLayout.setVerticalGroup(
            jOrderRegisterScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jOrderRegisterScreenLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jOrderRegisterScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jContainerScreens.add(jOrderRegisterScreen, "OrderRegisterScreen");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/customer-people.png"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(40, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel4.setText("Todo os clientes:");

        jTableCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTableCustomer);

        javax.swing.GroupLayout jCustomerRegisterScreenLayout = new javax.swing.GroupLayout(jCustomerRegisterScreen);
        jCustomerRegisterScreen.setLayout(jCustomerRegisterScreenLayout);
        jCustomerRegisterScreenLayout.setHorizontalGroup(
            jCustomerRegisterScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCustomerRegisterScreenLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jCustomerRegisterScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 906, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jCustomerRegisterScreenLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jCustomerRegisterScreenLayout.setVerticalGroup(
            jCustomerRegisterScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCustomerRegisterScreenLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jCustomerRegisterScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jContainerScreens.add(jCustomerRegisterScreen, "CustomerRegisterScreen");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/products.png"))); // NOI18N
        jLabel5.setMaximumSize(new java.awt.Dimension(40, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel6.setText("Registro de produtos:");

        jTableProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTableProduct);

        javax.swing.GroupLayout jProductRegisterScreenLayout = new javax.swing.GroupLayout(jProductRegisterScreen);
        jProductRegisterScreen.setLayout(jProductRegisterScreenLayout);
        jProductRegisterScreenLayout.setHorizontalGroup(
            jProductRegisterScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jProductRegisterScreenLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jProductRegisterScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 906, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jProductRegisterScreenLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jProductRegisterScreenLayout.setVerticalGroup(
            jProductRegisterScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jProductRegisterScreenLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jProductRegisterScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jContainerScreens.add(jProductRegisterScreen, "ProductRegisterScreen");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/payment.png"))); // NOI18N
        jLabel7.setMaximumSize(new java.awt.Dimension(40, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel8.setText("Regitro de pagamentos:");

        jTablePayment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTablePayment);

        javax.swing.GroupLayout jPymentRegisterScreenLayout = new javax.swing.GroupLayout(jPymentRegisterScreen);
        jPymentRegisterScreen.setLayout(jPymentRegisterScreenLayout);
        jPymentRegisterScreenLayout.setHorizontalGroup(
            jPymentRegisterScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPymentRegisterScreenLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPymentRegisterScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 906, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPymentRegisterScreenLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPymentRegisterScreenLayout.setVerticalGroup(
            jPymentRegisterScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPymentRegisterScreenLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPymentRegisterScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jContainerScreens.add(jPymentRegisterScreen, "PymentRegisterScreen");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/inventory.png"))); // NOI18N
        jLabel9.setMaximumSize(new java.awt.Dimension(40, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel10.setText("Reistro de estoques:");

        jTableInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableInventory);

        javax.swing.GroupLayout jInventoryRegisterScreenLayout = new javax.swing.GroupLayout(jInventoryRegisterScreen);
        jInventoryRegisterScreen.setLayout(jInventoryRegisterScreenLayout);
        jInventoryRegisterScreenLayout.setHorizontalGroup(
            jInventoryRegisterScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInventoryRegisterScreenLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jInventoryRegisterScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 906, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInventoryRegisterScreenLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jInventoryRegisterScreenLayout.setVerticalGroup(
            jInventoryRegisterScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInventoryRegisterScreenLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jInventoryRegisterScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jContainerScreens.add(jInventoryRegisterScreen, "InventoryRegisterScreen");

        jRegistersMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/registers-screens.png"))); // NOI18N
        jRegistersMenu.setText("Registros");

        jOrderMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/pedido.png"))); // NOI18N
        jOrderMenuItem.setText("Pedidos");
        jOrderMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOrderMenuItemActionPerformed(evt);
            }
        });
        jRegistersMenu.add(jOrderMenuItem);

        jCustomerMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/customer-screens.png"))); // NOI18N
        jCustomerMenuItem.setText("Clientes");
        jCustomerMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCustomerMenuItemActionPerformed(evt);
            }
        });
        jRegistersMenu.add(jCustomerMenuItem);

        jProductMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/product-screens.png"))); // NOI18N
        jProductMenuItem.setText("Produtos");
        jProductMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProductMenuItemActionPerformed(evt);
            }
        });
        jRegistersMenu.add(jProductMenuItem);

        jPaymentMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/pagamento.png"))); // NOI18N
        jPaymentMenuItem.setText("Pagamentos");
        jPaymentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPaymentMenuItemActionPerformed(evt);
            }
        });
        jRegistersMenu.add(jPaymentMenuItem);

        jInventoryMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/estoque.png"))); // NOI18N
        jInventoryMenuItem.setText("Estoque");
        jInventoryMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInventoryMenuItemActionPerformed(evt);
            }
        });
        jRegistersMenu.add(jInventoryMenuItem);

        jMenuBar.add(jRegistersMenu);

        jCustomerMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/customer-screens.png"))); // NOI18N
        jCustomerMenu.setText("Clientes");

        jCustomerRegisterMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/edit.png"))); // NOI18N
        jCustomerRegisterMenuItem.setText("Cadastrar");
        jCustomerRegisterMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCustomerRegisterMenuItemActionPerformed(evt);
            }
        });
        jCustomerMenu.add(jCustomerRegisterMenuItem);

        jCustomerUpdateMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/changes.png"))); // NOI18N
        jCustomerUpdateMenuItem.setText("Alterar");
        jCustomerMenu.add(jCustomerUpdateMenuItem);

        jCustomerRemoveMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/delete.png"))); // NOI18N
        jCustomerRemoveMenuItem.setText("Excluir");
        jCustomerMenu.add(jCustomerRemoveMenuItem);

        jMenuBar.add(jCustomerMenu);

        jProductMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/product-screens.png"))); // NOI18N
        jProductMenu.setText("Produtos");

        jProductRegisterMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/edit.png"))); // NOI18N
        jProductRegisterMenuItem.setText("Cadastrar");
        jProductRegisterMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProductRegisterMenuItemActionPerformed(evt);
            }
        });
        jProductMenu.add(jProductRegisterMenuItem);

        jProductUpdateMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/changes.png"))); // NOI18N
        jProductUpdateMenuItem.setText("Alterar");
        jProductMenu.add(jProductUpdateMenuItem);

        jProductRemoveMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/delete.png"))); // NOI18N
        jProductRemoveMenuItem.setText("Excluir");
        jProductMenu.add(jProductRemoveMenuItem);

        jMenuBar.add(jProductMenu);

        jOrderMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/pedido-screens.png"))); // NOI18N
        jOrderMenu.setText("Pedido");

        jOrderRegisterMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/edit.png"))); // NOI18N
        jOrderRegisterMenuItem.setText("Cadastrar");
        jOrderMenu.add(jOrderRegisterMenuItem);

        jOrderUpdateMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/changes.png"))); // NOI18N
        jOrderUpdateMenuItem.setText("Alterar");
        jOrderMenu.add(jOrderUpdateMenuItem);

        jOrderRemoveMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/delete.png"))); // NOI18N
        jOrderRemoveMenuItem.setText("Excluir");
        jOrderMenu.add(jOrderRemoveMenuItem);

        jMenuBar.add(jOrderMenu);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jContainerScreens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jContainerScreens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jProductMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProductMenuItemActionPerformed
        // TODO add your handling code here:
        CardLayout dl = (CardLayout) jContainerScreens.getLayout();
        dl.show(jContainerScreens, "ProductRegisterScreen");
    }//GEN-LAST:event_jProductMenuItemActionPerformed

    private void jCustomerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCustomerMenuItemActionPerformed
        // TODO add your handling code here:
        CardLayout dl = (CardLayout) jContainerScreens.getLayout();
        dl.show(jContainerScreens, "CustomerRegisterScreen");
    }//GEN-LAST:event_jCustomerMenuItemActionPerformed

    private void jOrderMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOrderMenuItemActionPerformed
        // TODO add your handling code here:
        CardLayout dl = (CardLayout) jContainerScreens.getLayout();
        dl.show(jContainerScreens, "OrderRegisterScreen");
    }//GEN-LAST:event_jOrderMenuItemActionPerformed

    private void jPaymentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPaymentMenuItemActionPerformed
        // TODO add your handling code here:
        CardLayout dl = (CardLayout) jContainerScreens.getLayout();
        dl.show(jContainerScreens, "PymentRegisterScreen");
    }//GEN-LAST:event_jPaymentMenuItemActionPerformed

    private void jInventoryMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInventoryMenuItemActionPerformed
        // TODO add your handling code here:
        CardLayout dl = (CardLayout) jContainerScreens.getLayout();
        dl.show(jContainerScreens, "InventoryRegisterScreen");
    }//GEN-LAST:event_jInventoryMenuItemActionPerformed

    private void jCustomerRegisterMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCustomerRegisterMenuItemActionPerformed
        // TODO add your handling code here:
        CardLayout dl = (CardLayout) jContainerScreens.getLayout();
        dl.show(jContainerScreens, "RegisterScreen");
        
        jScreen.add(createCustomer);
        createCustomer.setVisible(true);
    }//GEN-LAST:event_jCustomerRegisterMenuItemActionPerformed

    private void jProductRegisterMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProductRegisterMenuItemActionPerformed
        // TODO add your handling code here:
        CardLayout dl = (CardLayout) jContainerScreens.getLayout();
        dl.show(jContainerScreens, "RegisterScreen");
        
        jScreen.add(createProduct);
        createProduct.setVisible(true);
    }//GEN-LAST:event_jProductRegisterMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Pay frame = new Pay();
//                frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jContainerScreens;
    private javax.swing.JMenu jCustomerMenu;
    private javax.swing.JMenuItem jCustomerMenuItem;
    private javax.swing.JMenuItem jCustomerRegisterMenuItem;
    private javax.swing.JPanel jCustomerRegisterScreen;
    private javax.swing.JMenuItem jCustomerRemoveMenuItem;
    private javax.swing.JMenuItem jCustomerUpdateMenuItem;
    private javax.swing.JMenuItem jInventoryMenuItem;
    private javax.swing.JPanel jInventoryRegisterScreen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jOrderMenu;
    private javax.swing.JMenuItem jOrderMenuItem;
    private javax.swing.JMenuItem jOrderRegisterMenuItem;
    private javax.swing.JPanel jOrderRegisterScreen;
    private javax.swing.JMenuItem jOrderRemoveMenuItem;
    private javax.swing.JMenuItem jOrderUpdateMenuItem;
    private javax.swing.JMenuItem jPaymentMenuItem;
    private javax.swing.JMenu jProductMenu;
    private javax.swing.JMenuItem jProductMenuItem;
    private javax.swing.JMenuItem jProductRegisterMenuItem;
    private javax.swing.JPanel jProductRegisterScreen;
    private javax.swing.JMenuItem jProductRemoveMenuItem;
    private javax.swing.JMenuItem jProductUpdateMenuItem;
    private javax.swing.JPanel jPymentRegisterScreen;
    private javax.swing.JPanel jRegisterScreen;
    private javax.swing.JMenu jRegistersMenu;
    private javax.swing.JDesktopPane jScreen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTableCustomer;
    private javax.swing.JTable jTableInventory;
    private javax.swing.JTable jTableOrder;
    private javax.swing.JTable jTablePayment;
    private javax.swing.JTable jTableProduct;
    // End of variables declaration//GEN-END:variables
}
